# Generated by Django 6.0.1 on 2026-02-08 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_add_company_settings_fields'),
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyImportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('data_types', models.JSONField(default=list, help_text='List of data types to import from this file')),
                ('tally_company_name', models.CharField(blank=True, max_length=255)),
                ('tally_version', models.CharField(blank=True, max_length=50)),
                ('export_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('IMPORTING', 'Importing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('successful_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('skipped_records', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(default=dict, help_text='Import options like overwrite, skip_duplicates, etc.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tally_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tally Import Job',
                'verbose_name_plural': 'Tally Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TallyFieldMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of this mapping configuration', max_length=100)),
                ('data_type', models.CharField(choices=[('LEDGER_GROUP', 'Ledger Groups (Account Groups)'), ('LEDGER', 'Ledgers'), ('STOCK_GROUP', 'Stock Groups'), ('STOCK_ITEM', 'Stock Items'), ('STOCK_CATEGORY', 'Stock Categories'), ('UNIT', 'Units of Measure'), ('GODOWN', 'Godowns (Warehouses)'), ('PARTY', 'Parties (Customers/Suppliers)'), ('VOUCHER', 'Vouchers'), ('COST_CENTER', 'Cost Centers'), ('COST_CATEGORY', 'Cost Categories'), ('CURRENCY', 'Currencies'), ('OPENING_BALANCE', 'Opening Balances')], max_length=30)),
                ('field_mappings', models.JSONField(default=dict, help_text='JSON mapping of Tally field names to system field names')),
                ('value_transformations', models.JSONField(default=dict, help_text="Value transformation rules (e.g., Tally 'Dr' -> 'DEBIT')")),
                ('default_values', models.JSONField(default=dict, help_text='Default values for fields not in Tally export')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default mapping for this data type')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name': 'Tally Field Mapping',
                'verbose_name_plural': 'Tally Field Mappings',
                'unique_together': {('company', 'name', 'data_type')},
            },
        ),
        migrations.CreateModel(
            name='TallyImportRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('LEDGER_GROUP', 'Ledger Groups (Account Groups)'), ('LEDGER', 'Ledgers'), ('STOCK_GROUP', 'Stock Groups'), ('STOCK_ITEM', 'Stock Items'), ('STOCK_CATEGORY', 'Stock Categories'), ('UNIT', 'Units of Measure'), ('GODOWN', 'Godowns (Warehouses)'), ('PARTY', 'Parties (Customers/Suppliers)'), ('VOUCHER', 'Vouchers'), ('COST_CENTER', 'Cost Centers'), ('COST_CATEGORY', 'Cost Categories'), ('CURRENCY', 'Currencies'), ('OPENING_BALANCE', 'Opening Balances')], max_length=30)),
                ('tally_id', models.CharField(blank=True, max_length=255)),
                ('tally_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('DUPLICATE', 'Duplicate')], default='PENDING', max_length=20)),
                ('source_data', models.JSONField(default=dict, help_text='Original Tally data')),
                ('converted_data', models.JSONField(default=dict, help_text='Converted system data')),
                ('created_object_id', models.CharField(blank=True, max_length=50)),
                ('created_object_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('validation_errors', models.JSONField(default=list)),
                ('source_line', models.IntegerField(blank=True, null=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='system.tallyimportjob')),
            ],
            options={
                'ordering': ['source_line', 'created_at'],
                'indexes': [models.Index(fields=['import_job', 'status'], name='system_tall_import__4589c1_idx'), models.Index(fields=['import_job', 'data_type'], name='system_tall_import__519afc_idx')],
            },
        ),
        migrations.CreateModel(
            name='TallyMasterMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('LEDGER_GROUP', 'Ledger Groups (Account Groups)'), ('LEDGER', 'Ledgers'), ('STOCK_GROUP', 'Stock Groups'), ('STOCK_ITEM', 'Stock Items'), ('STOCK_CATEGORY', 'Stock Categories'), ('UNIT', 'Units of Measure'), ('GODOWN', 'Godowns (Warehouses)'), ('PARTY', 'Parties (Customers/Suppliers)'), ('VOUCHER', 'Vouchers'), ('COST_CENTER', 'Cost Centers'), ('COST_CATEGORY', 'Cost Categories'), ('CURRENCY', 'Currencies'), ('OPENING_BALANCE', 'Opening Balances')], max_length=30)),
                ('tally_name', models.CharField(db_index=True, max_length=255)),
                ('tally_guid', models.CharField(blank=True, max_length=100)),
                ('system_id', models.UUIDField()),
                ('system_model', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_mappings', to='system.tallyimportjob')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'data_type', 'tally_name'], name='system_tall_company_7ecda2_idx')],
                'unique_together': {('company', 'data_type', 'tally_name')},
            },
        ),
    ]
