# Generated by Django 6.0.1 on 2026-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_tallyimportjob_tallyfieldmapping_tallyimportrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyimportjob',
            name='xml_content',
            field=models.TextField(blank=True, help_text='Cached XML content for import processing'),
        ),
    ]
