# Generated by Django 6.0.1 on 2026-02-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_add_xml_content_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tallyfieldmapping',
            table='system_tallyfieldmapping',
        ),
        migrations.AlterModelTable(
            name='tallyimportjob',
            table='system_tallyimportjob',
        ),
        migrations.AlterModelTable(
            name='tallyimportrecord',
            table='system_tallyimportrecord',
        ),
        migrations.AlterModelTable(
            name='tallymastermapping',
            table='system_tallymastermapping',
        ),
    ]
