# Generated by Django 6.0.1 on 2026-02-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_allow_nullable_ledger'),
        ('portal', '0002_alter_retaileruser_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailercompanyaccess',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_accesses', to='party.retaileruser'),
        ),
    ]
