# Generated by Django 5.1.6 on 2026-02-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_make_phoneotp_user_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset')], default='registration', max_length=20),
        ),
    ]
